version: '3'
services: 
  mongodb:
    image: mongo
    volumes:
      - /vol/oremote/data/zwrapper:/data/db
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb