version: '3.8'
services: 
  mongodb:
    image: mongo
    volumes:
      - /vol/zwrapper/data/db:/data/db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"