version: '3'
services: 
  mongodb:
    image: mongo
    volumes:
      - /vol/zwrapper/data/db:/data/db
    restart: always
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"